In [1]:
import torch
from d2l import torch as d2l

In [2]:
X = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
X.sum(0, keepdim=True), X.sum(1, keepdim=True)

(tensor([[5., 7., 9.]]),
 tensor([[ 6.],
         [15.]]))

In [3]:
def softmax(X):
    X_exp = torch.exp(X)
    partition = X_exp.sum(1, keepdim=True)
    return X_exp / partition  # The broadcasting mechanism is applied here

In [4]:
X = torch.rand(2,5)
X_prob = softmax(X)
X_prob, X_prob.sum(1)  # Check that the sum of each row is 1

(tensor([[0.2009, 0.1186, 0.1699, 0.2228, 0.2878],
         [0.2151, 0.2231, 0.2218, 0.1602, 0.1797]]),
 tensor([1., 1.]))

In [5]:
## Softmanx regex

In [15]:
class SoftmaxRegressionScratch(d2l.Module):
    def __init__(self,num_inputs,num_outputs,lr,sigma=0.1):
        super().__init__()
        self.save_hyperparameters()
        self.w = torch.normal(0,sigma,size=(num_inputs,num_outputs),requires_grad=True)
        self.b = torch.zeros(num_outputs,requires_grad=True)
    
    def parameters(self):
        return [self.w,self.b]

In [16]:
## add to class
def forward(self,X):
    X = X.reshape((-1,self.w.shape[0]))
    return softmax(torch.matmul(X,self.w)+self.b)




In [17]:
## cross entropy loss
y = torch.tensor([0, 2])
y_hat = torch.tensor([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])
# Pick the probabilities corresponding to the correct labels
y_hat[[0, 1], y]

tensor([0.1000, 0.5000])

In [18]:
def cross_entropy(y_hat, y):
    return - torch.log(y_hat[range(len(y_hat)), y]).mean()


In [19]:
cross_entropy(y_hat, y)

tensor(1.4979)

In [20]:
@d2l.add_to_class(d2l.Module)  #@save
def loss(self, y_hat, y):
    return cross_entropy(y_hat, y)

In [21]:
## Training

In [25]:
data = d2l.FashionMNIST(batch_size=256)
model = SoftmaxRegressionScratch(num_inputs=784,num_outputs=10,lr=0.1)
trainer = d2l.Trainer(max_epochs=10)

In [26]:
trainer.fit(model, data)

AssertionError: Neural network is defined